---
title: "Exploratory phylogenetic analysis"
output: html_document
---


```{r}
library(here)
library(ape)
library(phangorn)
library(tidyverse)
```

Read in matrix

```{r}
snps <- read.phyDat(here("analysis", "data", "Laura_ALL_ms_FINAL_80complete.snps.phy"),
                    format = "phylip")
```


Create a neighbor joining tree

```{r}
dist_mat <- dist.ml(snps)

tree_nj <- NJ(dist_mat)
```

Set iheringii as outgroup for visualization.  

```{r}
out_group <- tree_nj$tip.label %>% 
  .[str_starts(tree_nj$tip.label, "ihe_")]

plot(root(tree_nj, out_group))
```


Cut tip labels for vis  

```{r}
tree_nj_cut <- tree_nj

# get prefixes
tree_nj_cut$tip.label <- str_extract(tree_nj_cut$tip.label, "[a-z]+") %>% 
  paste0(1:length(tree_nj_cut$tip.label))


out_cut <- tree_nj_cut$tip.label %>% 
  .[str_starts(tree_nj_cut$tip.label, "ihe")]

tree_nj_cut <- root(tree_nj_cut, out_cut)

#View full tree
# plot(tree_nj_cut)

# zoom in on a particular taxon
zoom(tree_nj_cut, focus = tree_nj_cut$tip.label[str_starts(tree_nj_cut$tip.label, "per")])

```

Now use the taxon labels from Mariana to check on putative species  

```{r}
mariana_df <- readxl::read_excel(here("analysis", "data", "Enyalius_Seq_FINAL.xlsx"))

tree_nj_sp <- tree_nj

tree_nj_sp$tip.label <- str_remove(tree_nj_sp$tip.label, "_concat")

tree_nj_sp$tip.label[tree_nj_sp$tip.label %in% mariana_df$ID_code] <- 
  str_c(mariana_df$Species[mariana_df$ID_code %in% tree_nj_sp$tip.label], "_", mariana_df$ID_code[mariana_df$ID_code %in% tree_nj_sp$tip.label])

zoom(tree_nj_sp, focus = tree_nj_sp$tip.label[str_starts(tree_nj_sp$tip.label, "per")])
```





