# missing 90 because I ran an assembly for it first before running the other assemnblies
CLUSTBRANCHES: [88, 92, 94, 96, 98]

CLUSTTHRESH: [88, 92, 94, 96, 98]

# param with 90 included
CLUSTTHRESHFULL: [88, 90, 92, 94, 96, 98]

SPLONG: ["catenatus", "iheringii", "perditus", "pictus", "all"]

INLONG: ["catenatus", "iheringii", "perditus", "pictus"]

OUTSHORT: ["agr", "alo", "uva"]

SNPPATHS: ["full/clust88_outfiles/clust88.snps.hdf5", "full/full_clust90_outfiles/full_clust90.snps.hdf5", "full/clust92_outfiles/clust92.snps.hdf5", "full/clust94_outfiles/clust94.snps.hdf5", "full/clust96_outfiles/clust96.snps.hdf5", "full/clust98_outfiles/clust98.snps.hdf5"]

SHAREOUT: ["full/sharing_matrices/"]

PCABATCHOUT: ["full/pca_batch/"]

PCACLUSTOUT: ["full/pca_clust/"]

# ipyrad stats paths fully specified because of lame full_clust90 path specification
IPSTATS: ["full/clust88_outfiles/clust88_stats.txt", "full/full_clust90_outfiles/full_clust90_stats.txt", "full/clust92_outfiles/clust92_stats.txt", "full/clust94_outfiles/clust94_stats.txt", "full/clust96_outfiles/clust96_stats.txt", "full/clust98_outfiles/clust98_stats.txt"]
